import { NextRequest, NextResponse } from 'next/server'
import connectDB from '@/lib/mongodb'
import Transcript from '@/models/Transcript'
import { verifyToken } from '@/lib/jwt'

// GET - جلب نص الفيديو
export async function GET(request: NextRequest) {
  try {
    await connectDB()

    const { searchParams } = new URL(request.url)
    const lessonId = searchParams.get('lessonId')
    const language = searchParams.get('language') || 'ar'

    if (!lessonId) {
      return NextResponse.json({ success: false, message: 'معرف الدرس مطلوب' }, { status: 400 })
    }

    const transcript = await Transcript.findOne({
      lesson: lessonId,
      language,
    })

    return NextResponse.json({
      success: true,
      transcript,
    })
  } catch (error) {
    console.error('Error fetching transcript:', error)
    return NextResponse.json({ success: false, message: 'حدث خطأ' }, { status: 500 })
  }
}

// POST - إضافة/تحديث نص الفيديو (للمدرس/الأدمن)
export async function POST(request: NextRequest) {
  try {
    await connectDB()

    const token = request.cookies.get('token')?.value
    if (!token) {
      return NextResponse.json({ success: false, message: 'غير مصرح' }, { status: 401 })
    }

    const decoded = verifyToken(token)
    if (!decoded || !['admin', 'instructor'].includes(decoded.role)) {
      return NextResponse.json({ success: false, message: 'غير مصرح' }, { status: 403 })
    }

    const body = await request.json()
    const { lessonId, courseId, language, segments, isAutoGenerated } = body

    if (!lessonId || !courseId || !segments) {
      return NextResponse.json({ success: false, message: 'بيانات ناقصة' }, { status: 400 })
    }

    // إنشاء النص الكامل للبحث
    const fullText = segments.map((s: any) => s.text).join(' ')

    const transcript = await Transcript.findOneAndUpdate(
      { lesson: lessonId, language: language || 'ar' },
      {
        lesson: lessonId,
        course: courseId,
        language: language || 'ar',
        segments,
        fullText,
        isAutoGenerated: isAutoGenerated || false,
      },
      { upsert: true, new: true }
    )

    return NextResponse.json({
      success: true,
      transcript,
    })
  } catch (error) {
    console.error('Error saving transcript:', error)
    return NextResponse.json({ success: false, message: 'حدث خطأ' }, { status: 500 })
  }
}

// DELETE - حذف نص الفيديو
export async function DELETE(request: NextRequest) {
  try {
    await connectDB()

    const token = request.cookies.get('token')?.value
    if (!token) {
      return NextResponse.json({ success: false, message: 'غير مصرح' }, { status: 401 })
    }

    const decoded = verifyToken(token)
    if (!decoded || !['admin', 'instructor'].includes(decoded.role)) {
      return NextResponse.json({ success: false, message: 'غير مصرح' }, { status: 403 })
    }

    const { searchParams } = new URL(request.url)
    const lessonId = searchParams.get('lessonId')

    if (!lessonId) {
      return NextResponse.json({ success: false, message: 'معرف الدرس مطلوب' }, { status: 400 })
    }

    await Transcript.deleteMany({ lesson: lessonId })

    return NextResponse.json({
      success: true,
      message: 'تم حذف النص',
    })
  } catch (error) {
    console.error('Error deleting transcript:', error)
    return NextResponse.json({ success: false, message: 'حدث خطأ' }, { status: 500 })
  }
}
