import mongoose, { Schema, Document, Model } from 'mongoose'

export interface ITranscriptSegment {
  startTime: number
  endTime: number
  text: string
}

export interface ITranscript extends Document {
  lesson: mongoose.Types.ObjectId
  course: mongoose.Types.ObjectId
  language: string
  segments: ITranscriptSegment[]
  fullText: string // النص الكامل للبحث
  isAutoGenerated: boolean
  createdAt: Date
  updatedAt: Date
}

const TranscriptSegmentSchema = new Schema({
  startTime: { type: Number, required: true },
  endTime: { type: Number, required: true },
  text: { type: String, required: true },
})

const TranscriptSchema = new Schema<ITranscript>(
  {
    lesson: {
      type: Schema.Types.ObjectId,
      ref: 'Lesson',
      required: true,
    },
    course: {
      type: Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    language: {
      type: String,
      default: 'ar',
    },
    segments: [TranscriptSegmentSchema],
    fullText: {
      type: String,
      default: '',
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
)

// Index for search
TranscriptSchema.index({ lesson: 1, language: 1 }, { unique: true })
TranscriptSchema.index({ fullText: 'text' })

const Transcript: Model<ITranscript> =
  mongoose.models.Transcript || mongoose.model<ITranscript>('Transcript', TranscriptSchema)

export default Transcript
